blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
# Used for SSL Certificat at : https://www.httpcs.com/
# from .views import security_txt  

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
    path('mdeditor/', include('mdeditor.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('resume/', include('resume.urls')),
    path('contact/', include('contact.urls')),
    # Used for SSL Certificat at : https://www.httpcs.com/
    # path(".well-known/pki-validation/EC523B3318EF62A7C00C36E8629DF486.txt", security_txt),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)

contact/urls.py
from django.urls import path

from .views import contactView

app_name = 'contact'

urlpatterns = [
    path('', contactView, name='email'),
]

contact/models.py
from django.db import models

# Create your models here.

contact/forms.py
# sendemail/forms.py
from django import forms

class ContactForm(forms.Form):
    name = forms.CharField(required=True)
    from_email = forms.EmailField(required=True)
    subject = forms.CharField(required=True)
    message = forms.CharField(widget=forms.Textarea, required=True)

contact/views.py
# sendemail/views.py
from django.core.mail import send_mail, BadHeaderError
from django.shortcuts import render, redirect
from django.conf import settings
from django.contrib import messages
from .forms import ContactForm

def contactView(request):
    if request.method == 'GET':
        form = ContactForm()
    else:
        form = ContactForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            subject = form.cleaned_data['subject']
            from_email = form.cleaned_data['from_email']
            message = form.cleaned_data['message']
            try:
                send_mail(
                    subject=f"[Blog] - {subject}",
                    message=f"Message de la part de {name} - {from_email}: \n {message}",
                    from_email=settings.DEFAULT_FROM_EMAIL,
                    recipient_list=[settings.DEFAULT_FROM_EMAIL]
                )
                messages.success(request, 'Votre message a bien été envoyé.')
            except BadHeaderError:
                messages.error(request, "Le formulaire est incomplet, le message n'est pas parti.")
            return redirect('contact:email')
    return render(request, "contact.html", {'form': form})

contact/templates/contact.html
{% extends 'base.html' %}
{% load static %}

{% comment %} META {% endcomment %}
{% block title %}
  Contact - {{ block.super }}
{% endblock title %}

{% block description %}Formulaire de contact.{% endblock description %}

{% block keywords %}{{ block.super }}, contact, message, mail, contactez-nous, contacter, contrat, mission{% endblock keywords %}

{% comment %} Extras {% endcomment %}
{% block extrajs %}
{% endblock extrajs %}

{% block extracss %}
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'css/contact.css' %}">
{% endblock extracss %}

{% comment %} Content {% endcomment %}
{% block content %}
<section id="contact">
  
    <h1 class="section-header">Contact</h1>
    
    <div class="contact-wrapper">
    
    <!-- Left contact page -->      
      <form id="contact-form" class="form-horizontal" role="form" method="post">
        {% csrf_token %}
        <div class="form-group">
          <div class="col-sm-12">
            <input type="text" class="form-control" id="id_name" placeholder="NOM" name="name" value="" required>
          </div>
        </div>
  
        <div class="form-group">
          <div class="col-sm-12">
            <input type="email" class="form-control" id="id_from_email" placeholder="EMAIL" name="from_email" value="" required>
          </div>
        </div>
        <div class="form-group">
          <div class="col-sm-12">
            <input type="text" class="form-control" id="id_subject" placeholder="OBJET" name="subject" value="" required>
          </div>
        </div>

        <textarea class="form-control" rows="10" id="id_message" placeholder="MESSAGE" name="message" required></textarea>
        
        <button class="btn btn-primary send-button" id="submit" type="submit" value="ENVOYER">
          <div class="alt-send-button">
            <i class="fa fa-paper-plane"></i><span class="send-text">ENVOYER</span>
          </div>
        
        </button>
        
      </form>
      
    <!-- Left contact page --> 
      
        <div class="direct-contact-container">
          <ul class="contact-list">
            <li class="list-item"><i class="fa fa-map-marker fa-2x"><span class="contact-text place">Annecy, France</span></i></li>
            <li class="list-item"><i class="fa fa-phone fa-2x"><span class="contact-text phone"><a href="tel:+33777046599" title="Appelez-moi">(+33) 7-77-04-65-99</a></span></i></li>
            <li class="list-item"><i class="fa fa-envelope fa-2x"><span class="contact-text gmail"><a href="mailto:Emericdefay@gmail.com" title="Envoyez-moi un email">Emericdefay@gmail.com</a></span></i></li>
          </ul>
          <hr>
          <ul class="social-media-list">
            <li><a href="https://github.com/Emericdefay" target="_blank" class="contact-icon">
              <i class="fab fa-github" aria-hidden="true"></i></a>
            </li>
            <li><a href="https://www.linkedin.com/in/emericdefay/" target="_blank" class="contact-icon">
              <i class="fab fa-linkedin" aria-hidden="true"></i></a>
            </li>       
            {% comment %} <li><a href="#" target="_blank" class="contact-icon">
              <i class="fab fa-codepen" aria-hidden="true"></i></a>
            </li>
            <li><a href="#" target="_blank" class="contact-icon">
              <i class="fab fa-twitter" aria-hidden="true"></i></a>
            </li> {% endcomment %}
          </ul>
          <hr>
  
          <div class="copyright">N'hésitez pas</div>
  
        </div>
      
    </div>
    
  </section>  
{% endblock content %}

contact/templates/email.html
{% extends 'base.html' %}
{% load static %}
{% load markdown_extras %}
{% load comment_tags %}

{% block title %}
{{ post.title }} - {{ block.super }}
{% endblock title %}

{% block content %}

  <!-- templates/email.html -->
  <h1>Contact Us</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <div class="form-actions">
      <button type="submit">Send</button>
    </div>
  </form>
{% endblock content %}