blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
# Used for SSL Certificat at : https://www.httpcs.com/
# from .views import security_txt  

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
    path('mdeditor/', include('mdeditor.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('resume/', include('resume.urls')),
    path('contact/', include('contact.urls')),
    # Used for SSL Certificat at : https://www.httpcs.com/
    # path(".well-known/pki-validation/EC523B3318EF62A7C00C36E8629DF486.txt", security_txt),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)

contact/urls.py
from django.urls import path

from .views import contactView

app_name = 'contact'

urlpatterns = [
    path('', contactView, name='email'),
]

posts/urls.py
from django.urls import path

from posts import views

app_name = 'posts'

urlpatterns = [
    path('', views.PostListView.as_view(), name='post-list'),
    path('post/create/', views.PostCreateView.as_view(), name='post-create'),
    path('post/<slug:slug>/', views.PostDetailView.as_view(),
         name='post-detail'),
    path('post/<slug:slug>/update/', views.PostUpdateView.as_view(),
         name='post-update'),
    path('post/<slug:slug>/delete/', views.PostDeleteView.as_view(),
         name='post-delete'),
    path('tag/<slug:slug>/', views.TagDetailView.as_view(),
         name='tag-detail'),
]

resume/urls.py
from django.urls import path

from . import views

app_name = 'resume'

urlpatterns = [
    path('', views.some_view, name='body'),
]

templates/base.html
{% load i18n static %}

{% get_current_language as LANGUAGE_CODE %}
{% get_available_languages as LANGUAGES %}
{% get_language_info_list for LANGUAGES as languages %}


<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE }}">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv = "Content-type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="shortcut icon" type="image/png" href="{% static 'img/favicon.ico' %}"/>
    <meta name="description" content="{% block description %}Découvrons les subtilités de Django, la puissance du Machine Learning. Un blog qui se veut zen et ludique.{% endblock description %}">
    <meta name="keywords" content="{% block keywords %}développeur, python, django, emeric, defay, blog, machine learning, openclassrooms, medium, sklearn{% endblock keywords %}">
    <title>{% block title %}Dev.py{% endblock title %}</title>
    <meta rel="canonical" href="{{ request.get_full_path }}">
    <meta property="og:url" content="{{ request.build_absolute_uri }}">
    <meta property="og:site_name" content="Emericdefay">
    <meta name="twitter:site" content="@EmericDefay">
    {% block meta %}
      <meta property="og:type" content="website">
      <meta property="og:title" content="Dev.py - Blog pour développeur Django/Machine Learning">
      <meta property="og:description" content="Découvrons les subtilités de Django, la puissance du Machine Learning. Un blog qui se veut zen et ludique.">
      <meta property="og:image" content="{{ request.scheme }}://{{request.META.HTTP_HOST}}{% block thumbnail_img %}{% static 'img/thumbnail-mini.png' %}{% endblock thumbnail_img %}">
      <meta property="og:image:type" content="image/png">
      <meta property="og:image:width" content="79">
      <meta property="og:image:height" content="79">
      <meta name="twitter:card" content="{{ request.scheme }}://{{request.META.HTTP_HOST}}{% static 'img/thumbnail.png' %}">
      <meta name="twitter:image:alt" content="Développeur Django et Machine Learning">
    {% endblock meta %}

    <!--Preloading needed images -->
    {% block preload %}
    {% endblock preload %}
    <script src="{% static 'dist/index.js' %}"></script>
    <link rel="stylesheet" href="{% static 'dist/index.css' %}">
    {% block extracss %}
    {% endblock extracss %}
  </head>

  <body>
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark sticky-top d-print-none">
      <div class="container">
        <a class="navbar-brand" href="/">
          <h1 class="nav-title">Dev.py</h1>
        </a>
        <button class="navbar-toggler d-lg-none" type="button" data-bs-toggle="collapse" data-bs-target="#collapsibleNavId"
          aria-controls="collapsibleNavId" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="collapsibleNavId">
          <ul class="navbar-nav mt-2 mt-lg-0">
            {% if request.user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link {% if request.path == '/post/create/' %}active{% endif %}"
                href="{% url 'posts:post-create' %}">{% trans "Créer un post" %}</a>
            </li>
            {% endif %}
            <li class="nav-item">
              <a class="nav-link {% if request.path == '/' %}active{% endif %}" href="/">{% trans "Blog" %}</a>
            </li>
            {% comment %} <li class="nav-item">
              <a class="nav-link {% if request.path == '/project/' %}active{% endif %}" href="{% url "projects:list %}">{% trans "Projets" %}</a>
            </li> {% endcomment %}
            <li class="nav-item">
              <a class="nav-link {% if request.path == '/resume/' %}active{% endif %}" href="{% url "resume:body" %}">{% trans "Résumé" %}</a>
            </li>
            <li class="nav-item">
              <a class="nav-link {% if request.path == '/contact/' %}active{% endif %}" href="{% url "contact:email" %}">{% trans "Contact" %}</a>
            </li>
          </ul>
          <ul class="navbar-nav ms-auto">
            <button class="theme-toggler"><i class="far fa-sun"></i></button>
          </ul>
        </div>
      </div>
    </nav>

    {% if messages %}
    <div class="container my-3">
      {% for message in messages %}
        <div class="alert alert-{{ message.tags }} pt-2 article alert-dismissible fade show" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
            <span class="sr-only">{% trans "Close" %}</span>
          </button>
          {{ message }}
        </div>
      {% endfor %}
    </div>
    {% endif %}

    <canvas class="d-print-none" id="bgCanvas"></canvas>
    <div class="d-print-none cloud large cloud-1"><div></div><div></div><div></div><div></div></div>
    <div class="d-print-none cloud normal cloud-2"><div></div><div></div><div></div><div></div></div>
    <div class="d-print-none cloud small cloud-3"><div></div><div></div><div></div><div></div></div>
    <div class="d-print-none cloud tiny cloud-4"><div></div><div></div><div></div><div></div></div>
    <div class="d-print-none cloud large cloud-5"><div></div><div></div><div></div><div></div></div>
    <div class="d-print-none cloud normal cloud-6"><div></div><div></div><div></div><div></div></div>
    <div class="d-print-none cloud small cloud-7"><div></div><div></div><div></div><div></div></div>
    <div class="d-print-none cloud tiny cloud-8"><div></div><div></div><div></div><div></div></div>
    <div class="d-print-none cloud small cloud-9"><div></div><div></div><div></div><div></div></div>
    <div class="d-print-none cloud normal cloud-10"><div></div><div></div><div></div><div></div></div>
    <div class="d-print-none cloud tiny cloud-11"><div></div><div></div><div></div><div></div></div>
    <div class="d-print-none cloud small cloud-12"><div></div><div></div><div></div><div></div></div>

    <div class="container container-content my-3">
      {% block content %}
      
      {% endblock content %}
    </div>

    <script>
      window.app.setTheme();
      window.app.setBackground();
      window.app.makeBackground();
    </script>
    {% block extrajs %}
    {% endblock extrajs %}

    {% block extrascriptjs %}
    {% endblock extrascriptjs %}

  </body>
  <footer class="bg-dark py-3 d-print-none">
    <div class="container text-light">
      <div class="text-center">
        <p class="lead">&copy; 2022-{% now 'Y' %} <a class="text-light" href="/">Emeric Defay</a></p>
      </div>
    </div>
  </footer>
</html>