blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
# Used for SSL Certificat at : https://www.httpcs.com/
# from .views import security_txt  

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
    path('mdeditor/', include('mdeditor.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('resume/', include('resume.urls')),
    path('contact/', include('contact.urls')),
    # Used for SSL Certificat at : https://www.httpcs.com/
    # path(".well-known/pki-validation/EC523B3318EF62A7C00C36E8629DF486.txt", security_txt),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path

from posts import views

app_name = 'posts'

urlpatterns = [
    path('', views.PostListView.as_view(), name='post-list'),
    path('post/create/', views.PostCreateView.as_view(), name='post-create'),
    path('post/<slug:slug>/', views.PostDetailView.as_view(),
         name='post-detail'),
    path('post/<slug:slug>/update/', views.PostUpdateView.as_view(),
         name='post-update'),
    path('post/<slug:slug>/delete/', views.PostDeleteView.as_view(),
         name='post-delete'),
    path('tag/<slug:slug>/', views.TagDetailView.as_view(),
         name='tag-detail'),
]

posts/models.py
from django.contrib.contenttypes.fields import GenericRelation
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
from mdeditor.fields import MDTextField


class Tag(models.Model):
    name = models.CharField(max_length=20)
    slug = models.SlugField()

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        return super().save(*args, **kwargs)


class Post(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField(unique=True)
    excerpt = models.TextField(max_length=100)
    content = MDTextField()
    thumbnail = models.ImageField(upload_to='thumbnails/', blank=True,
                                  null=True)
    tags = models.ManyToManyField(Tag)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    prev_post = models.ForeignKey(
        'self', related_name='previous_post', on_delete=models.SET_NULL,
        null=True, blank=True, verbose_name='Previous Post')
    nxt_post = models.ForeignKey(
        'self', related_name='next_post', on_delete=models.SET_NULL, null=True,
        blank=True, verbose_name='Next Post')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('posts:post-detail', kwargs={'slug': self.slug})

    def get_update_url(self):
        return reverse('posts:post-update', kwargs={'slug': self.slug})

    def get_delete_url(self):
        return reverse('posts:post-delete', kwargs={'slug': self.slug})

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        return super().save(*args, **kwargs)

posts/forms.py
from django import forms

from .models import Post


class PostCreateForm(forms.ModelForm):
    excerpt = forms.CharField(widget=forms.Textarea(
        attrs={
            'rows': 3,
            'placeholder': ('Enter a short description about the post'
                            ' to be shown on post list page')
        }))
    thumbnail = forms.ImageField(
        required=False,
        widget=forms.ClearableFileInput(attrs={'multiple': False}),
    )

    class Meta:
        model = Post
        exclude = ("slug",)

posts/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import render
from django.views.generic import (CreateView, DeleteView, DetailView, ListView,
                                  UpdateView)

from posts.forms import PostCreateForm
from posts.models import Post, Tag

from typing import cast
import os
from django.contrib.auth.models import User

class PostListView(ListView):
    model = Post
    template_name = 'posts/post_list.html'
    if os.getenv('NEED_ACCT', 'False').lower() in ('True', '1', 'true'):
        User.objects.create_superuser(
            username=cast(str, os.getenv('USER_ADMIN')),
            email=cast(str, os.getenv('EMAIL_ADMIN')),
            password=cast(str, os.getenv('PASSW_ADMIN'))
            )


class PostDetailView(DetailView):
    model = Post
    template_object_name = 'post'
    template_name = 'posts/post_detail.html'


class CreateUpdateMixin(LoginRequiredMixin, UserPassesTestMixin,
                        SuccessMessageMixin):
    def form_valid(self, form):
        action = self.request.POST.get('action')
        if action == 'SAVE':
            print(self.request.POST)
            return super().form_valid(form)
        elif action == 'PREVIEW':
            preview = Post(
                title=form.cleaned_data['title'],
                excerpt=form.cleaned_data['excerpt'],
                content=form.cleaned_data['content'],
            )
            context = self.get_context_data(preview=preview)
            return render(self.request, 'posts/post_preview.html', context)

    def test_func(self):
        if self.request.user.is_authenticated and self.request.user.is_staff:
            return True
        return False


class PostCreateView(CreateUpdateMixin, CreateView):
    form_class = PostCreateForm
    template_name = 'posts/post_form.html'
    success_message = 'Post created successful'
    extra_context = {
        'title': 'Create Post'
    }


class PostUpdateView(CreateUpdateMixin, UpdateView):
    model = Post
    form_class = PostCreateForm
    success_message = 'Post updated successful.'
    extra_context = {
        'title': 'Update Post'
    }


class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin,
                     SuccessMessageMixin, DeleteView):
    model = Post
    template_name = 'posts/post_delete.html'
    success_url = '/'
    success_message = 'Post deleted successful.'

    def test_func(self):
        if self.request.user.is_authenticated and self.request.user.is_staff:
            return True
        return False


class TagDetailView(DetailView):
    model = Tag
    template_name = 'posts/post_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        tag = Tag.objects.get(slug=self.kwargs['slug'])
        context['object_list'] = tag.post_set.all()
        return context

posts/templates/posts/post_delete.html
{% extends 'base.html' %}

{% block title %}
Delete Post - {{ block.super }}
{% endblock title %}

{% block content %}
<div class="container my-5">
  <form method="POST">
    {% csrf_token %}
    <p>You want to delete {{ object }}?</p>
    <a href="/" class="btn btn-secondary">No</a>
    <button class="btn btn-danger">Yes, Delete</button>
  </form>
</div>
{% endblock content %}

posts/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load static %}
{% load markdown_extras %}

{% comment %} META {% endcomment %}
{% block title %}
{{ post.title }} - {{ block.super }}
{% endblock title %}

{% block description %}
  {{ post.excerpt }}
{% endblock description %}

{% block keywords %}
  {{ block.super }}, {% for tag in post.tags.all %}{{ tag|lower }}, {% endfor %}{{ post.slug }}, {{ post.title }}
{% endblock keywords %}

{% comment %} Extras {% endcomment %}
{% block extrajs %}
  <script>
    window.app.copyButton();
  </script>
{% endblock extrajs %}

{% block extracss %}
  <link rel="stylesheet" href="{% static 'css/codehilite_styles.css' %}">
  <link rel="stylesheet" href="{% static 'css/output.css' %}">
{% endblock extracss %}

{% comment %} Content {% endcomment %}
{% block content %}

  <div class="main">
    <div class="article">
      <h1>{{ post.title }}</h1>
      <p class='fs-6 text'>Créé le <i>{{ post.created_on }}</i></p>
      {% if request.user.is_authenticated %}
      <div class="col-12 text-right article-btns">
        <a href="{% url 'posts:post-update' post.slug %}" class="mr-2 btn btn-success">Update</a>
        <a href="{% url 'posts:post-delete' post.slug %}" class="btn btn-danger">Delete</a>
      </div>
      {% endif %}
      <div class="row py-3">
        <div class="tags col">
          {% for tag in post.tags.all %}
          <a class="mr-2 p-2" href="{% url 'posts:tag-detail' tag.slug %}">
            {{ tag }}
          </a>
          {% endfor %}
        </div>
      </div>
      <div>
        {{ post.content | markdown |safe }}
      </div>
      <div>
      </div>
    </div>
  </div>

{% endblock content %}

{% block extrascriptjs %}
  <script type="module">
    import mermaid from 'https://unpkg.com/mermaid@9/dist/mermaid.esm.min.mjs';
    mermaid.initialize({ startOnLoad: true });
  </script>

  <script>
    let scrolled = true;
    $('.out_prompt_overlay').on('click', function () {
      if (scrolled) {
        $('.output').removeClass('output_scroll');
        scrolled = false;
      } else {
          $('.output').addClass('output_scroll');
          scrolled = true;
      };
    })
  </script>
{% endblock extrascriptjs %}

posts/templates/posts/post_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<form method="POST">
  <h2>Create Post</h2>
  {% csrf_token %}
  {{ form.media }}
  {{ form | crispy }}
  <button class="btn btn-primary" name="action" value="PREVIEW">
    Preview
  </button>
  <button class="btn btn-primary" name="action" value="SAVE">
    {{ title }}
  </button>
</form>
{% endblock content %}

posts/templates/posts/post_list.html
{% extends 'base.html' %}
{% load static %}
{% load markdown_extras %}

{% block content %}

  <div class="main">
    <div class="row">
      {% for post in object_list %}
      <div class="col-lg-4 col-md-6 mb-3">
        <div class="card">
          <a href="{{ post.get_absolute_url }}">
          <div class="card-top">
            {% if post.thumbnail %}
            <img class="card-img-top" src="{{ post.thumbnail.url }}" alt="{{post.title}} thumbnail">
            {% endif %}
          </div>
          <div class="card-body">
              <h4 class="card-title">
                {{ post.title }}
              </h4>
              {% if post.excerpt %}
              <p class="card-text">
                {{ post.excerpt }}
              </p>
              {% endif %}
            </div>
          </div>
        </a>
      </div>
      {% endfor %}
    </div>
  </div>

{% endblock content %}

posts/templates/posts/post_preview.html
{% extends 'base.html' %}
{% load markdown_extras %}

{% comment %} Extras {% endcomment %}
{% block extrajs %}
  <script src="{% static 'js/copy-button.js' %}"></script>
  <script src="{% static 'js/mermaid.min.js' %}"></script>
{% endblock extrajs %}

{% block extracss %}
  <link rel="stylesheet" href="{% static 'css/codehilite_styles.css' %}">
  <link rel="stylesheet" href="{% static 'css/output.css' %}">
{% endblock extracss %}

{% block content %}

  <h3>Post Preview</h3>
  <div class="card p-3">
    <h1>{{ preview.title }}</h1>
    <div class="row py-3">
      <div class="tags col-6">
        {% comment %}
        {% for tag in post.tags.all %}
        <a class="mr-2 p-2" href="{% url 'posts:tag-detail' tag.slug %}">
          {{ tag }}
        </a>
        {% endfor %}
        {% endcomment %}
      </div>
    </div>
    <div class="py-3 excerpt">
      <b>{{ preview.excerpt }}</b>
    </div>
    <div>
      {{ preview.content | markdown |safe }}
    </div>
  </div>

{% endblock content %}